[package]
name = "fibonacci-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "^1.0", features = ["api-all"] }

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3